export const GET_HELLO_MESSAGE_ERROR = "GET_HELLO_MESSAGE_ERROR";
export const SEARCH = "SEARCH";
export const SEARCH_1 = "SEARCH_1";
export const SEARCH_ACCESSORIES = "SEARCH_ACCESSORIES";
export const SEARCH_ACCESSORIES_1 = "SEARCH_ACCESSORIES_1";
export const SEARCH_ERROR = "SEARCH_ERROR";

/* Action types when password is forgotten  */
export const UPDATE_PASSWORD = "UPDATE_PASSWORD";
export const UPDATE_PASSWORD_ERROR = "UPDATE_PASSWORD_ERROR";

/* Check if user with this email made a forgot password request */
export const CHECK_EMAIL = "CHECK_EMAIL";
export const CHECK_EMAIL_ERROR = "CHECK_EMAIL_ERROR";

export const UPDATE_RATING = "UPDATE_RATING";
export const UPDATE_RATING_ERROR = "UPDATE_RATING_ERROR";
export const UPDATE_CUSTOMER = "UPDATE_CUSTOMER";
export const UPDATE_CUSTOMER_ERROR = "UPDATE_CUSTOMER_ERROR";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const GET_CUSTOMER_BY_ID = "GET_CUSTOMER_BY_ID";
export const GET_CUSTOMER_BY_ID_ERROR = "GET_CUSTOMER_BY_ID_ERROR";

export const EMAIL_VERIFIED = "EMAIL_VERIFIED";
export const EMAIL_VERIFICATION_FAILED = "EMAIL_VERIFICATION_FAILED";
export const GET_VEHICLE_BY_ID = "GET_VEHICLE_BY_ID";
export const GET_VEHICLE_BY_ID_ERROR = "GET_VEHICLE_BY_ID_ERROR";

export const PASSWORD_SUCCESS = "PASSWORD_SUCCESS";
export const PASSWORD_FAILED = "PASSWORD_FAILED";
export const RESET_CHANGE_PASSWORD_STORE = "RESET_CHANGE_PASSWORD_STORE";

export const SIGNUP = "SIGNUP";
export const SIGNUP_FAILED = "SIGNUP_FAILED";
export const SET_FILTER_ATTRIBUTES = "SET_FILTER_ATTRIBUTES";
export const FETCH_FILTERED_LIST = "FETCH_FILTERED_LIST";
export const FETCH_FILTERED_LIST_ERROR = "FETCH_FILTERED_LIST_ERROR";
export const GET_FAVORITE_VEHICLES = "GET_FAVORITE_VEHICLES";
export const GET_FAVORITE_VEHICLES_ERROR = "GET_FAVORITE_VEHICLES_ERROR";
export const UPDATE_FAVORITES = "UPDATE_FAVORITES";
export const UPDATE_FAVORITES_ERROR = "UPDATE_FAVORITES_ERROR";

export const ADD_REMOVE_BRAND = "ADD_REMOVE_BRAND";
export const ADD_REMOVE_VEHICLE_TYPE = "ADD_REMOVE_VEHICLE_TYPE";
export const ADD_REMOVE_FUEL_TYPE = "ADD_REMOVE_FUEL_TYPE";
export const ADD_REMOVE_VEHICLE_COLOR = "ADD_REMOVE_VEHICLE_COLOR";
export const ADD_REMOVE_AIRBAG_COUNT = "ADD_REMOVE_AIRBAG_COUNT";
export const ADD_REMOVE_YEAR = "ADD_REMOVE_YEAR";
export const ADD_REMOVE_PRICE = "ADD_REMOVE_PRICE";
export const UPDATE_PRICE = "UPDATE_PRICE";
export const UPDATE_YEAR = "UPDATE_YEAR";

/* for Vehicle comparison matrix*/
export const ADD_TO_COMPARE = "ADD_TO_COMPARE";
export const REMOVE_FROM_COMPARE = "REMOVE_FROM_COMPARE";
export const GET_SPONSORED_VEHICLE = "GET_SPONSORED_VEHICLE";
export const GET_SPONSORED_VEHICLE_ERROR = "GET_SPONSORED_VEHICLE_ERROR";
export const COMPARISON_MATRIX_METADATA = "COMPARISON_MATRIX_METADATA";
export const COMPARISON_MATRIX_METADATA_ERROR =
  "COMPARISON_MATRIX_METADATA_ERROR";
export const DELETE_MATRIX = "DELETE_MATRIX";

export const GET_VEHICLES = "GET_VEHICLES";
export const GET_VEHICLES_1 = "GET_VEHICLES_1";
export const GET_VEHICLES_ERROR = "GET_VEHICLES_ERROR";
export const SAVE_COMPARISON_MATRIX = "SAVE_COMPARISON_MATRIX";
export const SAVE_COMPARISON_MATRIX_ERROR = "SAVE_COMPARISON_MATRIX_ERROR";
export const GET_MY_REVIEW = "GET_MY_REVIEW";
export const GET_MY_REVIEW_ERROR = "GET_MY_REVIEW_ERROR";
export const POST_MY_REVIEW = "POST_MY_REVIEW";
export const POST_MY_REVIEW_ERROR = "POST_MY_REVIEW_ERROR";

export const GET_COMPARISON_BY_ID = "GET_COMPARISON_BY_ID";
export const GET_COMPARISON_BY_ID_ERROR = "GET_COMPARISON_BY_ID_ERROR";
export const GET_MY_RATING = "GET_MY_RATING";
export const GET_MY_RATING_ERROR = "GET_MY_RATING_ERROR";

export const UPDATE_VEHICLE_DETAILS = "UPDATE_VEHICLE_DETAILS";
export const UPDATE_VEHICLE_DETAILS_ERROR = "UPDATE_VEHICLE_DETAILS_ERROR";
export const GET_DEALER_UPLOADS = "GET_DEALER_UPLOADS";
export const GET_DEALER_UPLOADS_ERROR = "GET_DEALER_UPLOADS_ERROR";

export const ADD_VEHICLE = "ADD_VEHICLE";
export const ADD_VEHICLE_ERROR = "ADD_VEHICLE_ERROR";
export const RESET_ADD_VEHICLE = "RESET_ADD_VEHICLE";

export const FEEDBACK_SUCCESS = "FEEDBACK_SUCCESS";
export const FEEDBACK_FAILURE = "FEEDBACK_FAILURE";
export const GET_AVERAGE_RATING = "GET_MY_RATING";
export const GET_AVERAGE_RATING_ERROR = "GET_MY_RATING_ERROR";
export const VERIFY_CUSTOMER = "VERIFY_CUSTOMER";
export const VERIFY_CUSTOMER_ERROR = "VERIFY_CUSTOMER_ERROR";

export const UPLOAD_CSV = "UPLOAD_CSV";
export const UPLOAD_CSV_ERROR = "UPLOAD_CSV_ERROR";

// dealer vehicle reducer
export const GET_DEALER_VEHICLES = "GET_DEALER_VEHICLES";
export const SELECT_DEALER_VEHICLES = "SELECT_DEALER_VEHICLES";
export const REMOVE_SELECTED_DEALER_VEHICLES =
  "REMOVE_SELECTED_DEALER_VEHICLES";
export const FILTER_DEALER_VEHICLES = "FILTER_DEALER_VEHICLES";
export const NO_DEALER_VECHICLES_DISPATCH_ACTION =
  "NO_DEALER_VECHICLES_DISPATCH_ACTION";

export const GET_VEHICLE_FILTER_ATTRIBUTE = "GET_VEHICLE_FILTER_ATTRIBUTE";
export const GET_VEHICLE_FILTER_ATTRIBUTE_ERROR =
  "GET_VEHICLE_FILTER_ATTRIBUTE_ERROR";
export const UPDATE_VEHICLE_FILTER = "UPDATE_VEHICLE_FILTER";
export const UPLOAD_JSON = "UPLOAD_JSON";
export const UPLOAD_JSON_ERROR = "UPLOAD_JSON_ERROR";
export const GET_DEALER_REVIEWS = "GET_DEALER_REVIEWS";
export const GET_DEALER_REVIEWS_ERROR = "GET_DEALER_REVIEWS_ERROR";

// for vehicle accesories
export const GET_VEHICLE_ACCESSORY = "GET_VEHICLE_ACCESSORY";
export const GET_VEHICLE_ACCESSORY_ERROR = "GET_VEHICLE_ACCESSORY_ERROR";
export const DELETE_ACCESSORY = "DELETE_ACCESSORY";
export const ADD_ACCESSORY = "ADD_ACCESSORY";
export const ADD_ACCESSORY_ERROR = "ADD_ACCESSORY_ERROR";
export const RESET_ADD_ACCESSORY = "RESET_ADD_ACCESSORY";

export const RESET_DEALER_VEHICLE_STATE = "RESET_DEALER_VEHICLE_STATE";
export const RESET_SINGLE_VEHICLE_STATE = "RESET_SINGLE_VEHICLE_STATE";

export const RESET_FETCH_FILTERED_LIST = "RESET_FETCH_FILTERED_LIST";

// for vehicle compare
export const FETCH_VEHICLE_COMPARE = "FETCH_VEHICLE_COMPARE";
export const FETCH_VEHICLE_COMPARE_ERROR = "FETCH_VEHICLE_COMPARE_ERROR";
export const ADD_VEHICLE_TO_COMPARE = "ADD_VEHICLE_TO_COMPARE";
export const ADD_VEHICLE_TO_COMPARE_ERROR = "ADD_VEHICLE_TO_COMPARE_ERROR";

export const UPDATE_ACCESSORY_SUCCESS = "UPDATE_ACCESSORY_SUCCESS";
export const UPDATE_ACCESSORY_FAILED = "UPDATE_ACCESSORY_FAILED";
export const UPDATE_ACCESSORY_FAILED_WITH_RESPONSE =
  "UPDATE_ACCESSORY_FAILED_WITH_RESPONSE";
export const GET_DEALER_VEHICLE_ACCESSORIES = "GET_DEALER_VEHICLE_ACCESSORIES";
export const RESET_DEALER_VEHICLE_ACCESSORIES_STATE ="RESET_DEALER_VEHICLE_ACCESSORIES_STATE";
export const SELECT_DEALER_ACCESSORY = "SELECT_DEALER_ACCESSORY";
