server:
    port: 80

spring:
    application:
        name: GATEWAY-SERVICE
    cloud:
        gateway:
            routes:
                - id: productService
                  predicates:
                      - Path=/api/products/**
                  uri: lb://PRODUCT-SERVICE/

                - id: customerService
                  predicates:
                      - Path=/api/customers/**
                  uri: lb://CUSTOMER-SERVICE/

eureka:
    client:
        retisterWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
    instance:
        hostname: localhost
