@startuml

client actor


client -> Tomcat
Tomcat -> HttpServlet.service(ServletRequest, ServletResponse)
HttpServlet.service(ServletRequest, ServletResponse) -> HttpServlet.service(HttpServletRequest, HttpServletResponse)
HttpServlet.service(HttpServletRequest, HttpServletResponse) -> HelloServlet.doGet
@enduml