version: '2'

services:
    # docker run --name zookeeper -p 2181:2181 -v zookeeper_data:/bitnami docker.io/bitnami/zookeeper:3.7
    zookeeper:
        image: docker.io/bitnami/zookeeper:3.7
        ports:
            - '2181:2181'
        volumes:
            - 'zookeeper_data:/bitnami'
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes

    # docker run --name=kafka-server -p 9092:9092 -v kafka_data:/bitnami -e KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181 -e ALLOW_PLAINTEXT_LISTENER=yes docker.io/bitnami/kafka:2
    kafka-server:
        image: docker.io/bitnami/kafka:2
        ports:
            - '9092:9092'
        volumes:
            - 'kafka_data:/bitnami'
        environment:
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
        depends_on:
            - zookeeper
    rest-endpoint:
        image: learnwithvinod/rest-endpoint:latest
        ports:
            - '8080:8080'
        depends_on:
            - kafka-server
    reporting-service:
        image: learnwithvinod/reporting-service:latest
        depends_on:
            - kafka-server

volumes:
    zookeeper_data:
        driver: local
    kafka_data:
        driver: local
