@startuml

interface ProductDao {
    + add(product: Product): void
    + get(id: Integer): Product
    + update(product: Product): void
    + delete(id: Integer): void
    + getAll(): List<Product>
    + getByPriceRange(min: Double, max: Double): List<Product>
    + getByCategory(category: String): List<Product>
}

class ProductDaoJpaImpl {
    - getEntityManager(): EntityManger
    + add(product: Product): void
    + get(id: Integer): Product
    + update(product: Product): void
    + delete(id: Integer): void
    + getAll(): List<Product>
    + getByPriceRange(min: Double, max: Double): List<Product>
    + getByCategory(category: String): List<Product>
}

class DaoFactory{
    + static getProductDao(): ProductDao
}

DaoFactory - ProductDaoJpaImpl
ProductDao <|.. ProductDaoJpaImpl


note left of DaoFactory: Manufactures instances of different DAO classes


@enduml