server:
    port: 8300

spring:
    application:
        name: PRODUCT-SERVICE


eureka:
    client:
        retisterWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
    instance:
        hostname: localhost

# spring:
#     datasource:
#         url: jdbc:mysql://localhost/mydb
#         username: root
#         password: Welcome#123
#         driverClassName: com.mysql.cj.jdbc.Driver